#!/usr/bin/env python3
"""
Seed de Exercícios — LAPHIS
Popula a base de dados com 40+ exercícios comuns
Inclui imagens Unsplash e links de vídeos YouTube
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.core.db import engine, Base, SessionLocal
from src.core.models import Exercise

# Criar tabelas
Base.metadata.create_all(bind=engine)

EXERCISES = [
    # ==================== PEITO ====================
    {
        "name": "Supino Reto com Barra",
        "name_en": "Barbell Bench Press",
        "category": "peito",
        "muscle_primary": "Peitoral maior",
        "muscle_secondary": "Tríceps, Deltóide anterior",
        "difficulty": "intermedio",
        "equipment": "Barra, Banco",
        "image_url": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400",
        "video_url": "https://www.youtube.com/watch?v=rT7DgCr-3pg",
        "instructions": "1. Deita-te no banco com os pés no chão\n2. Agarra a barra ligeiramente mais larga que os ombros\n3. Baixa a barra até ao peito controladamente\n4. Empurra até extensão completa\n5. Mantém as omoplatas retraídas",
        "tips": "Mantém os cotovelos a 45° do corpo. Não arquees excessivamente as costas.",
        "common_mistakes": "Levantar os glúteos do banco, bounce no peito, cotovelos muito abertos",
        "default_sets": 4,
        "default_reps": "6-8",
        "default_rest_sec": 120,
        "is_compound": 1,
        "calories_per_min": 8.5
    },
    {
        "name": "Supino Inclinado com Halteres",
        "name_en": "Incline Dumbbell Press",
        "category": "peito",
        "muscle_primary": "Peitoral superior (clavicular)",
        "muscle_secondary": "Tríceps, Deltóide anterior",
        "difficulty": "intermedio",
        "equipment": "Halteres, Banco inclinado",
        "image_url": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400",
        "video_url": "https://www.youtube.com/watch?v=8iPEnn-ltC8",
        "instructions": "1. Ajusta o banco a 30-45°\n2. Segura os halteres ao nível do peito\n3. Empurra para cima convergindo ligeiramente\n4. Baixa controladamente até sentir stretch\n5. Repete mantendo tensão constante",
        "tips": "Ângulo de 30° trabalha mais peito, 45° mais ombros. Não batas os halteres no topo.",
        "common_mistakes": "Ângulo muito alto (vira press de ombros), deixar cair os halteres",
        "default_sets": 3,
        "default_reps": "8-12",
        "default_rest_sec": 90,
        "is_compound": 1,
        "calories_per_min": 7.5
    },
    {
        "name": "Crucifixo com Halteres",
        "name_en": "Dumbbell Fly",
        "category": "peito",
        "muscle_primary": "Peitoral maior",
        "muscle_secondary": "Deltóide anterior",
        "difficulty": "iniciante",
        "equipment": "Halteres, Banco",
        "image_url": "https://images.unsplash.com/photo-1598971457999-ca4ef48a9a71?w=400",
        "video_url": "https://www.youtube.com/watch?v=eozdVDA78K0",
        "instructions": "1. Deita no banco com halteres sobre o peito\n2. Abre os braços em arco com cotovelos ligeiramente fletidos\n3. Baixa até sentir stretch no peito\n4. Fecha em arco como se abraçasses uma árvore",
        "tips": "Mantém cotovelos fixos a ~20°. Foca na contração do peito, não no peso.",
        "common_mistakes": "Braços demasiado retos (stressing ombros), peso excessivo",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_sec": 60,
        "is_compound": 0,
        "calories_per_min": 5.0
    },
    {
        "name": "Flexões",
        "name_en": "Push-Ups",
        "category": "peito",
        "muscle_primary": "Peitoral maior",
        "muscle_secondary": "Tríceps, Deltóide anterior, Core",
        "difficulty": "iniciante",
        "equipment": "Peso corporal",
        "image_url": "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400",
        "video_url": "https://www.youtube.com/watch?v=IODxDxX7oi4",
        "instructions": "1. Posição de prancha com mãos à largura dos ombros\n2. Corpo em linha reta dos calcanhares à cabeça\n3. Baixa o peito até quase tocar o chão\n4. Empurra até extensão completa\n5. Mantém core contraído",
        "tips": "Variações: diamante (tríceps), larga (peito), inclinada (mais fácil), declinada (mais difícil)",
        "common_mistakes": "Quadris a cair, cotovelos muito abertos, não descer totalmente",
        "default_sets": 3,
        "default_reps": "10-20",
        "default_rest_sec": 60,
        "is_compound": 1,
        "calories_per_min": 7.0
    },
    
    # ==================== COSTAS ====================
    {
        "name": "Deadlift (Levantamento Terra)",
        "name_en": "Deadlift",
        "category": "costas",
        "muscle_primary": "Eretores da espinha, Glúteos, Isquiotibiais",
        "muscle_secondary": "Trapézio, Antebraços, Core",
        "difficulty": "avancado",
        "equipment": "Barra, Discos",
        "image_url": "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400",
        "video_url": "https://www.youtube.com/watch?v=op9kVnSso6Q",
        "instructions": "1. Pés à largura das ancas, barra sobre o meio do pé\n2. Agarra a barra fora dos joelhos\n3. Peito para cima, costas neutras\n4. Empurra o chão com os pés\n5. Bloqueia ancas e joelhos no topo\n6. Desce controladamente",
        "tips": "A barra deve subir em linha reta. Pensa em 'empurrar o chão' em vez de 'puxar a barra'.",
        "common_mistakes": "Costas arredondadas, barra longe do corpo, joelhos a ceder para dentro",
        "default_sets": 4,
        "default_reps": "5-6",
        "default_rest_sec": 180,
        "is_compound": 1,
        "calories_per_min": 12.0
    },
    {
        "name": "Remada com Barra",
        "name_en": "Barbell Row",
        "category": "costas",
        "muscle_primary": "Grande dorsal, Romboides",
        "muscle_secondary": "Trapézio, Bíceps, Eretores",
        "difficulty": "intermedio",
        "equipment": "Barra",
        "image_url": "https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=400",
        "video_url": "https://www.youtube.com/watch?v=FWJR5Ve8bnQ",
        "instructions": "1. Pés à largura das ancas, joelhos ligeiramente fletidos\n2. Inclina o tronco a ~45°\n3. Agarra a barra ligeiramente mais larga que os ombros\n4. Puxa até à parte inferior do peito/umbigo\n5. Baixa controladamente",
        "tips": "Pensa em puxar com os cotovelos, não com as mãos. Mantém costas neutras.",
        "common_mistakes": "Usar momentum/balanço, costas arredondadas, não contrair omoplatas",
        "default_sets": 4,
        "default_reps": "8-10",
        "default_rest_sec": 90,
        "is_compound": 1,
        "calories_per_min": 8.0
    },
    {
        "name": "Pull-ups (Elevações)",
        "name_en": "Pull-Ups",
        "category": "costas",
        "muscle_primary": "Grande dorsal",
        "muscle_secondary": "Bíceps, Romboides, Trapézio inferior",
        "difficulty": "intermedio",
        "equipment": "Barra fixa",
        "image_url": "https://images.unsplash.com/photo-1597347316205-36f6c451902a?w=400",
        "video_url": "https://www.youtube.com/watch?v=eGo4IYlbE5g",
        "instructions": "1. Agarra a barra com pegada pronada (palmas para fora)\n2. Mãos ligeiramente mais largas que os ombros\n3. Puxa até o queixo passar a barra\n4. Baixa controladamente até extensão quase completa\n5. Evita balanço",
        "tips": "Inicia o movimento deprimindo as omoplatas. Se não conseguires, usa banda elástica.",
        "common_mistakes": "Kipping/balanço excessivo, não subir totalmente, não descer totalmente",
        "default_sets": 3,
        "default_reps": "6-12",
        "default_rest_sec": 120,
        "is_compound": 1,
        "calories_per_min": 9.0
    },
    {
        "name": "Lat Pulldown",
        "name_en": "Lat Pulldown",
        "category": "costas",
        "muscle_primary": "Grande dorsal",
        "muscle_secondary": "Bíceps, Trapézio",
        "difficulty": "iniciante",
        "equipment": "Máquina de cabos",
        "image_url": "https://images.unsplash.com/photo-1584466977773-e625c37cdd50?w=400",
        "video_url": "https://www.youtube.com/watch?v=CAwf7n6Luuc",
        "instructions": "1. Senta com coxas sob os rolos\n2. Agarra a barra mais larga que os ombros\n3. Inclina ligeiramente para trás\n4. Puxa até ao peito superior\n5. Controla a subida",
        "tips": "Foca em puxar com os cotovelos, não com as mãos. Contrai as omoplatas.",
        "common_mistakes": "Inclinar demais para trás, puxar atrás do pescoço, usar momentum",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_sec": 75,
        "is_compound": 1,
        "calories_per_min": 6.0
    },
    {
        "name": "Remada Unilateral com Halter",
        "name_en": "Dumbbell Row",
        "category": "costas",
        "muscle_primary": "Grande dorsal, Romboides",
        "muscle_secondary": "Bíceps, Trapézio",
        "difficulty": "iniciante",
        "equipment": "Halter, Banco",
        "image_url": "https://images.unsplash.com/photo-1532029837206-abbe2b7620e3?w=400",
        "video_url": "https://www.youtube.com/watch?v=pYcpY20QaE8",
        "instructions": "1. Apoia mão e joelho no banco\n2. Costas paralelas ao chão\n3. Halter na mão livre, braço estendido\n4. Puxa o cotovelo para trás e para cima\n5. Aperta omoplatas no topo",
        "tips": "Mantém a anca nivelada, não rodes o tronco. Pensa em iniciar com as costas.",
        "common_mistakes": "Rodar o tronco, usar momentum, não contrair no topo",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_sec": 60,
        "is_compound": 1,
        "calories_per_min": 6.5
    },
    
    # ==================== PERNAS ====================
    {
        "name": "Agachamento com Barra",
        "name_en": "Barbell Squat",
        "category": "pernas",
        "muscle_primary": "Quadricípites, Glúteos",
        "muscle_secondary": "Isquiotibiais, Eretores, Core",
        "difficulty": "intermedio",
        "equipment": "Barra, Rack",
        "image_url": "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400",
        "video_url": "https://www.youtube.com/watch?v=bEv6CCg2BC8",
        "instructions": "1. Barra nos trapézios, pés à largura dos ombros\n2. Pontas dos pés ligeiramente para fora\n3. Inspira, contrai o core\n4. Desce como se fosses sentar\n5. Joelhos na direção dos pés\n6. Sobe explosivamente",
        "tips": "Profundidade: pelo menos paralelo (coxas paralelas ao chão). Mantém calcanhares no chão.",
        "common_mistakes": "Joelhos a ceder para dentro, arredondar costas, não descer o suficiente",
        "default_sets": 4,
        "default_reps": "6-8",
        "default_rest_sec": 150,
        "is_compound": 1,
        "calories_per_min": 10.0
    },
    {
        "name": "Leg Press",
        "name_en": "Leg Press",
        "category": "pernas",
        "muscle_primary": "Quadricípites",
        "muscle_secondary": "Glúteos, Isquiotibiais",
        "difficulty": "iniciante",
        "equipment": "Máquina Leg Press",
        "image_url": "https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=400",
        "video_url": "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
        "instructions": "1. Senta com costas apoiadas\n2. Pés à largura dos ombros na plataforma\n3. Destrava e baixa controladamente\n4. Joelhos a ~90° (não locks no fundo)\n5. Empurra sem bloquear totalmente no topo",
        "tips": "Pés mais altos = mais glúteos/isquiotibiais. Pés mais baixos = mais quads.",
        "common_mistakes": "Arredondar lombar, bloquear joelhos totalmente, range of motion insuficiente",
        "default_sets": 4,
        "default_reps": "10-12",
        "default_rest_sec": 90,
        "is_compound": 1,
        "calories_per_min": 7.0
    },
    {
        "name": "Stiff (Romeno)",
        "name_en": "Romanian Deadlift",
        "category": "pernas",
        "muscle_primary": "Isquiotibiais, Glúteos",
        "muscle_secondary": "Eretores, Grande dorsal",
        "difficulty": "intermedio",
        "equipment": "Barra ou Halteres",
        "image_url": "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400",
        "video_url": "https://www.youtube.com/watch?v=JCXUYuzwNrM",
        "instructions": "1. Pés à largura das ancas, barra à frente das coxas\n2. Joelhos ligeiramente fletidos (fixos)\n3. Empurra a anca para trás\n4. Baixa a barra ao longo das pernas\n5. Sente stretch nos isquiotibiais\n6. Contrai glúteos para subir",
        "tips": "A barra deve manter-se junto às pernas. Foca no hip hinge, não em baixar a barra.",
        "common_mistakes": "Arredondar costas, fletir demais os joelhos, não sentir stretch",
        "default_sets": 3,
        "default_reps": "8-10",
        "default_rest_sec": 90,
        "is_compound": 1,
        "calories_per_min": 7.5
    },
    {
        "name": "Extensão de Pernas",
        "name_en": "Leg Extension",
        "category": "pernas",
        "muscle_primary": "Quadricípites",
        "muscle_secondary": "",
        "difficulty": "iniciante",
        "equipment": "Máquina",
        "image_url": "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=400",
        "video_url": "https://www.youtube.com/watch?v=YyvSfVjQeL0",
        "instructions": "1. Senta com costas apoiadas\n2. Rolo atrás dos tornozelos\n3. Estende as pernas até quase bloquear\n4. Contrai quads no topo\n5. Baixa controladamente",
        "tips": "Faz pausa no topo para máxima contração. Não uses momentum.",
        "common_mistakes": "Usar momentum, levantar glúteos do assento, range of motion incompleto",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_sec": 60,
        "is_compound": 0,
        "calories_per_min": 4.5
    },
    {
        "name": "Curl de Pernas Deitado",
        "name_en": "Lying Leg Curl",
        "category": "pernas",
        "muscle_primary": "Isquiotibiais",
        "muscle_secondary": "Gémeos",
        "difficulty": "iniciante",
        "equipment": "Máquina",
        "image_url": "https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=400",
        "video_url": "https://www.youtube.com/watch?v=1Tq3QdYUuHs",
        "instructions": "1. Deita-te de barriga para baixo\n2. Rolo atrás dos calcanhares\n3. Agarra os apoios\n4. Flete os joelhos trazendo calcanhares aos glúteos\n5. Baixa controladamente",
        "tips": "Mantém ancas em contacto com o banco. Faz pausa na contração.",
        "common_mistakes": "Levantar ancas, usar momentum, não fazer full range",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_sec": 60,
        "is_compound": 0,
        "calories_per_min": 4.5
    },
    {
        "name": "Lunges (Afundos)",
        "name_en": "Walking Lunges",
        "category": "pernas",
        "muscle_primary": "Quadricípites, Glúteos",
        "muscle_secondary": "Isquiotibiais, Core",
        "difficulty": "iniciante",
        "equipment": "Peso corporal ou Halteres",
        "image_url": "https://images.unsplash.com/photo-1434682772747-f16d3ea162c3?w=400",
        "video_url": "https://www.youtube.com/watch?v=QOVaHwm-Q6U",
        "instructions": "1. De pé, passo largo à frente\n2. Baixa até joelho traseiro quase tocar o chão\n3. Joelho da frente sobre o tornozelo\n4. Empurra para voltar ou avançar\n5. Alterna pernas",
        "tips": "Mantém tronco vertical. Passo mais longo = mais glúteos, mais curto = mais quads.",
        "common_mistakes": "Joelho a passar muito o pé, tronco inclinado, passos curtos",
        "default_sets": 3,
        "default_reps": "12 cada perna",
        "default_rest_sec": 60,
        "is_compound": 1,
        "calories_per_min": 8.0
    },
    {
        "name": "Elevação de Gémeos",
        "name_en": "Calf Raises",
        "category": "pernas",
        "muscle_primary": "Gastrocnémios (Gémeos)",
        "muscle_secondary": "Sóleo",
        "difficulty": "iniciante",
        "equipment": "Máquina ou Degrau",
        "image_url": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
        "video_url": "https://www.youtube.com/watch?v=gwLzBJYoWlI",
        "instructions": "1. Em pé, ponta dos pés num degrau/plataforma\n2. Calcanhares a pender para baixo (stretch)\n3. Sobe o máximo em ponta dos pés\n4. Contrai gémeos no topo\n5. Baixa controladamente",
        "tips": "Full range of motion é crucial. Pausa de 1s no topo e no fundo.",
        "common_mistakes": "Range of motion curto, não fazer pausa, usar bounce",
        "default_sets": 4,
        "default_reps": "15-20",
        "default_rest_sec": 45,
        "is_compound": 0,
        "calories_per_min": 4.0
    },
    
    # ==================== OMBROS ====================
    {
        "name": "Press Militar com Barra",
        "name_en": "Overhead Press",
        "category": "ombros",
        "muscle_primary": "Deltóide anterior e lateral",
        "muscle_secondary": "Tríceps, Trapézio superior, Core",
        "difficulty": "intermedio",
        "equipment": "Barra",
        "image_url": "https://images.unsplash.com/photo-1581009146145-b5ef050c149a?w=400",
        "video_url": "https://www.youtube.com/watch?v=2yjwXTZQDDI",
        "instructions": "1. Barra à altura das clavículas\n2. Mãos ligeiramente mais largas que ombros\n3. Contrai core e glúteos\n4. Empurra a barra verticalmente\n5. Cabeça avança ligeiramente quando a barra passa\n6. Bloqueia no topo",
        "tips": "Mantém o corpo rígido, não arquees as costas. A trajetória da barra deve ser reta.",
        "common_mistakes": "Arquear demais as costas, não bloquear no topo, usar pernas",
        "default_sets": 4,
        "default_reps": "6-8",
        "default_rest_sec": 120,
        "is_compound": 1,
        "calories_per_min": 7.0
    },
    {
        "name": "Elevação Lateral",
        "name_en": "Lateral Raises",
        "category": "ombros",
        "muscle_primary": "Deltóide lateral",
        "muscle_secondary": "Trapézio superior",
        "difficulty": "iniciante",
        "equipment": "Halteres",
        "image_url": "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=400",
        "video_url": "https://www.youtube.com/watch?v=3VcKaXpzqRo",
        "instructions": "1. De pé, halteres ao lado do corpo\n2. Cotovelos ligeiramente fletidos\n3. Eleva lateralmente até altura dos ombros\n4. Cotovelos sempre acima das mãos\n5. Baixa controladamente",
        "tips": "Pensa em derramar água de uma garrafa (roda ligeiramente no topo). Usa peso leve.",
        "common_mistakes": "Peso excessivo, balanço do corpo, subir acima dos ombros",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_sec": 60,
        "is_compound": 0,
        "calories_per_min": 4.0
    },
    {
        "name": "Face Pull",
        "name_en": "Face Pull",
        "category": "ombros",
        "muscle_primary": "Deltóide posterior, Trapézio médio",
        "muscle_secondary": "Romboides, Rotadores externos",
        "difficulty": "iniciante",
        "equipment": "Cabo com corda",
        "image_url": "https://images.unsplash.com/photo-1534368786749-b63e05c90863?w=400",
        "video_url": "https://www.youtube.com/watch?v=rep-qVOkqgk",
        "instructions": "1. Cabo à altura da cara\n2. Pega na corda com pegada neutra\n3. Puxa para o rosto separando as mãos\n4. Cotovelos para cima e para trás\n5. Contrai omoplatas\n6. Volta controladamente",
        "tips": "Excelente para saúde dos ombros e postura. Faz 15-20 reps com controlo.",
        "common_mistakes": "Peso excessivo, não separar as mãos, não contrair omoplatas",
        "default_sets": 3,
        "default_reps": "15-20",
        "default_rest_sec": 45,
        "is_compound": 0,
        "calories_per_min": 3.5
    },
    {
        "name": "Arnold Press",
        "name_en": "Arnold Press",
        "category": "ombros",
        "muscle_primary": "Deltóide anterior, lateral e posterior",
        "muscle_secondary": "Tríceps",
        "difficulty": "intermedio",
        "equipment": "Halteres",
        "image_url": "https://images.unsplash.com/photo-1532384555668-bc0f6e76a66f?w=400",
        "video_url": "https://www.youtube.com/watch?v=6Z15_WdXmVw",
        "instructions": "1. Sentado, halteres à frente (pegada supinada)\n2. Roda enquanto empurras para cima\n3. No topo, palmas viradas para fora\n4. Inverte o movimento para baixar\n5. Movimento fluido e controlado",
        "tips": "Criado pelo Arnold Schwarzenegger. Trabalha todas as cabeças do deltóide.",
        "common_mistakes": "Rotação demasiado rápida, não fazer full range, peso excessivo",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_sec": 75,
        "is_compound": 1,
        "calories_per_min": 6.0
    },
    
    # ==================== BÍCEPS ====================
    {
        "name": "Curl com Barra",
        "name_en": "Barbell Curl",
        "category": "biceps",
        "muscle_primary": "Bíceps braquial",
        "muscle_secondary": "Braquial, Braquiorradial",
        "difficulty": "iniciante",
        "equipment": "Barra reta ou EZ",
        "image_url": "https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400",
        "video_url": "https://www.youtube.com/watch?v=kwG2ipFRgfo",
        "instructions": "1. De pé, barra com pegada supinada\n2. Cotovelos junto ao corpo\n3. Flete os braços subindo a barra\n4. Contrai bíceps no topo\n5. Baixa controladamente",
        "tips": "Mantém cotovelos fixos. Usa barra EZ para menos stress nos pulsos.",
        "common_mistakes": "Balanço do corpo, cotovelos a moverem-se, não contrair no topo",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_sec": 60,
        "is_compound": 0,
        "calories_per_min": 5.0
    },
    {
        "name": "Curl Inclinado",
        "name_en": "Incline Dumbbell Curl",
        "category": "biceps",
        "muscle_primary": "Bíceps (cabeça longa)",
        "muscle_secondary": "Braquial",
        "difficulty": "intermedio",
        "equipment": "Halteres, Banco inclinado",
        "image_url": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400",
        "video_url": "https://www.youtube.com/watch?v=soxrZlIl35U",
        "instructions": "1. Banco a 45-60°\n2. Braços a pender com halteres\n3. Flete um braço mantendo cotovelo fixo\n4. Contrai no topo\n5. Alterna ou faz ambos",
        "tips": "O ângulo inclinado estica mais a cabeça longa do bíceps. Peso moderado.",
        "common_mistakes": "Cotovelos a avançar, balanço, não fazer full stretch",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_sec": 60,
        "is_compound": 0,
        "calories_per_min": 4.5
    },
    {
        "name": "Curl Martelo",
        "name_en": "Hammer Curl",
        "category": "biceps",
        "muscle_primary": "Braquiorradial, Braquial",
        "muscle_secondary": "Bíceps",
        "difficulty": "iniciante",
        "equipment": "Halteres",
        "image_url": "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=400",
        "video_url": "https://www.youtube.com/watch?v=zC3nLlEvin4",
        "instructions": "1. De pé, halteres com pegada neutra (palmas para dentro)\n2. Cotovelos junto ao corpo\n3. Flete subindo os halteres\n4. Mantém pegada neutra todo o tempo\n5. Baixa controladamente",
        "tips": "Trabalha o braquial que 'empurra' o bíceps. Bom para antebraços também.",
        "common_mistakes": "Rodar os pulsos, balanço do corpo, cotovelos a moverem-se",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_sec": 60,
        "is_compound": 0,
        "calories_per_min": 4.5
    },
    
    # ==================== TRÍCEPS ====================
    {
        "name": "Tricep Dips",
        "name_en": "Tricep Dips",
        "category": "triceps",
        "muscle_primary": "Tríceps",
        "muscle_secondary": "Peitoral inferior, Deltóide anterior",
        "difficulty": "intermedio",
        "equipment": "Barras paralelas",
        "image_url": "https://images.unsplash.com/photo-1530822847156-5df684ec5ee1?w=400",
        "video_url": "https://www.youtube.com/watch?v=2z8JmcrW-As",
        "instructions": "1. Agarra as barras paralelas\n2. Braços estendidos, corpo suspenso\n3. Cotovelos junto ao corpo\n4. Baixa até cotovelos a 90°\n5. Empurra até extensão completa",
        "tips": "Tronco vertical = mais tríceps. Inclinado para frente = mais peito.",
        "common_mistakes": "Descer demais (stress ombros), cotovelos a abrir, não bloquear",
        "default_sets": 3,
        "default_reps": "8-12",
        "default_rest_sec": 90,
        "is_compound": 1,
        "calories_per_min": 7.0
    },
    {
        "name": "Extensão de Tríceps na Polia",
        "name_en": "Tricep Pushdown",
        "category": "triceps",
        "muscle_primary": "Tríceps",
        "muscle_secondary": "",
        "difficulty": "iniciante",
        "equipment": "Cabo com barra ou corda",
        "image_url": "https://images.unsplash.com/photo-1571388208497-71bedc66e932?w=400",
        "video_url": "https://www.youtube.com/watch?v=2-LAMcpzODU",
        "instructions": "1. Cabo alto, barra/corda à frente\n2. Cotovelos junto ao corpo\n3. Estende empurrando para baixo\n4. Bloqueia cotovelos no fundo\n5. Volta controladamente até 90°",
        "tips": "Com corda, separa as mãos no fundo para mais contração. Cotovelos fixos!",
        "common_mistakes": "Cotovelos a moverem-se, inclinar corpo, não bloquear",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_sec": 45,
        "is_compound": 0,
        "calories_per_min": 4.0
    },
    {
        "name": "Skull Crushers",
        "name_en": "Skull Crushers",
        "category": "triceps",
        "muscle_primary": "Tríceps (cabeça longa)",
        "muscle_secondary": "",
        "difficulty": "intermedio",
        "equipment": "Barra EZ ou Halteres, Banco",
        "image_url": "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400",
        "video_url": "https://www.youtube.com/watch?v=d_KZxkY_0cM",
        "instructions": "1. Deitado no banco, barra sobre o peito\n2. Braços perpendiculares ao chão\n3. Flete cotovelos baixando para a testa\n4. Mantém braços fixos\n5. Estende até posição inicial",
        "tips": "Baixar atrás da cabeça estica mais a cabeça longa. Usa peso moderado.",
        "common_mistakes": "Cotovelos a abrir, peso excessivo, não fazer full range",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_sec": 60,
        "is_compound": 0,
        "calories_per_min": 5.0
    },
    
    # ==================== ABDÓMEN ====================
    {
        "name": "Prancha (Plank)",
        "name_en": "Plank",
        "category": "abdomen",
        "muscle_primary": "Transverso abdominal, Reto abdominal",
        "muscle_secondary": "Oblíquos, Eretores, Ombros",
        "difficulty": "iniciante",
        "equipment": "Peso corporal",
        "image_url": "https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=400",
        "video_url": "https://www.youtube.com/watch?v=pSHjTRCQxIw",
        "instructions": "1. Apoio nos antebraços e pontas dos pés\n2. Corpo em linha reta\n3. Contrai abdominais e glúteos\n4. Olhar para o chão\n5. Mantém a posição",
        "tips": "Não deixes a anca subir ou descer. Respira normalmente.",
        "common_mistakes": "Anca muito alta ou baixa, não contrair core, segurar respiração",
        "default_sets": 3,
        "default_reps": "30-60 seg",
        "default_rest_sec": 45,
        "is_compound": 1,
        "calories_per_min": 4.0
    },
    {
        "name": "Crunch",
        "name_en": "Crunch",
        "category": "abdomen",
        "muscle_primary": "Reto abdominal superior",
        "muscle_secondary": "",
        "difficulty": "iniciante",
        "equipment": "Peso corporal",
        "image_url": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
        "video_url": "https://www.youtube.com/watch?v=Xyd_fa5zoEU",
        "instructions": "1. Deitado, joelhos fletidos, pés no chão\n2. Mãos atrás da cabeça (não puxes)\n3. Contrai abdominais elevando ombros\n4. Exhala enquanto sobes\n5. Baixa controladamente",
        "tips": "Foca em 'aproximar costelas das ancas'. Não puxes o pescoço.",
        "common_mistakes": "Puxar o pescoço, usar momentum, range excessivo",
        "default_sets": 3,
        "default_reps": "15-20",
        "default_rest_sec": 45,
        "is_compound": 0,
        "calories_per_min": 5.0
    },
    {
        "name": "Leg Raises (Elevação de Pernas)",
        "name_en": "Hanging Leg Raises",
        "category": "abdomen",
        "muscle_primary": "Reto abdominal inferior, Flexores da anca",
        "muscle_secondary": "Oblíquos",
        "difficulty": "intermedio",
        "equipment": "Barra fixa",
        "image_url": "https://images.unsplash.com/photo-1597347316205-36f6c451902a?w=400",
        "video_url": "https://www.youtube.com/watch?v=hdng3Nm1x_E",
        "instructions": "1. Pendurado na barra com pegada pronada\n2. Pernas juntas e esticadas\n3. Eleva as pernas até 90° ou mais\n4. Contrai abdominais no topo\n5. Baixa controladamente",
        "tips": "Para mais difícil, sobe até aos braços. Para mais fácil, flete os joelhos.",
        "common_mistakes": "Balanço excessivo, não controlar descida, flexores mais que abs",
        "default_sets": 3,
        "default_reps": "10-15",
        "default_rest_sec": 60,
        "is_compound": 0,
        "calories_per_min": 6.0
    },
    {
        "name": "Russian Twist",
        "name_en": "Russian Twist",
        "category": "abdomen",
        "muscle_primary": "Oblíquos",
        "muscle_secondary": "Reto abdominal, Flexores da anca",
        "difficulty": "iniciante",
        "equipment": "Peso corporal ou Peso",
        "image_url": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
        "video_url": "https://www.youtube.com/watch?v=wkD8rjkodUI",
        "instructions": "1. Sentado, joelhos fletidos, pés levantados\n2. Inclina tronco ligeiramente para trás\n3. Roda tronco para um lado\n4. Toca o chão/peso ao lado\n5. Roda para o outro lado",
        "tips": "Mantém peito aberto e roda do tronco, não só os braços.",
        "common_mistakes": "Só rodar braços, deixar pés no chão, arredondar costas",
        "default_sets": 3,
        "default_reps": "20 total",
        "default_rest_sec": 45,
        "is_compound": 0,
        "calories_per_min": 5.0
    },
    {
        "name": "Dead Bug",
        "name_en": "Dead Bug",
        "category": "abdomen",
        "muscle_primary": "Transverso abdominal, Core profundo",
        "muscle_secondary": "Reto abdominal",
        "difficulty": "iniciante",
        "equipment": "Peso corporal",
        "image_url": "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400",
        "video_url": "https://www.youtube.com/watch?v=I5xbsA71v1A",
        "instructions": "1. Deitado, braços para cima, joelhos a 90°\n2. Pressiona lombar no chão\n3. Estende braço e perna opostos\n4. Mantém lombar em contacto\n5. Volta e alterna",
        "tips": "Excelente para estabilidade do core. Foca em manter lombar no chão.",
        "common_mistakes": "Arquear lombar, mover demasiado rápido, não coordenar",
        "default_sets": 3,
        "default_reps": "10 cada lado",
        "default_rest_sec": 45,
        "is_compound": 0,
        "calories_per_min": 4.0
    },
    
    # ==================== CARDIO ====================
    {
        "name": "Burpees",
        "name_en": "Burpees",
        "category": "cardio",
        "muscle_primary": "Full body",
        "muscle_secondary": "Peito, Pernas, Core, Ombros",
        "difficulty": "intermedio",
        "equipment": "Peso corporal",
        "image_url": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400",
        "video_url": "https://www.youtube.com/watch?v=JZQA08SlJnM",
        "instructions": "1. De pé, agacha e coloca mãos no chão\n2. Salta pés para trás (posição flexão)\n3. Faz uma flexão\n4. Salta pés para as mãos\n5. Salta explosivamente com braços para cima",
        "tips": "Para mais fácil: remove a flexão e/ou o salto. Mantém ritmo constante.",
        "common_mistakes": "Não fazer flexão completa, não estender no salto, perder forma",
        "default_sets": 3,
        "default_reps": "10-15",
        "default_rest_sec": 60,
        "is_compound": 1,
        "calories_per_min": 14.0
    },
    {
        "name": "Mountain Climbers",
        "name_en": "Mountain Climbers",
        "category": "cardio",
        "muscle_primary": "Core, Flexores da anca",
        "muscle_secondary": "Ombros, Pernas",
        "difficulty": "iniciante",
        "equipment": "Peso corporal",
        "image_url": "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400",
        "video_url": "https://www.youtube.com/watch?v=nmwgirgXLYM",
        "instructions": "1. Posição de prancha alta\n2. Traz um joelho ao peito\n3. Alterna rapidamente as pernas\n4. Mantém anca baixa e estável\n5. Ritmo contínuo",
        "tips": "Mantém core apertado. Velocidade conforme nível de fitness.",
        "common_mistakes": "Anca muito alta, perder forma, não trazer joelhos o suficiente",
        "default_sets": 3,
        "default_reps": "30-45 seg",
        "default_rest_sec": 45,
        "is_compound": 1,
        "calories_per_min": 11.0
    },
    {
        "name": "Jumping Jacks",
        "name_en": "Jumping Jacks",
        "category": "cardio",
        "muscle_primary": "Full body, Cardiovascular",
        "muscle_secondary": "Ombros, Pernas",
        "difficulty": "iniciante",
        "equipment": "Peso corporal",
        "image_url": "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400",
        "video_url": "https://www.youtube.com/watch?v=c4DAnQ6DtF8",
        "instructions": "1. De pé, braços ao lado\n2. Salta abrindo pernas e braços\n3. Mãos tocam acima da cabeça\n4. Salta voltando à posição inicial\n5. Ritmo contínuo",
        "tips": "Bom para aquecimento. Mantém movimentos controlados.",
        "common_mistakes": "Não abrir bem, não coordenar, aterrar com joelhos rígidos",
        "default_sets": 3,
        "default_reps": "30-60 seg",
        "default_rest_sec": 30,
        "is_compound": 1,
        "calories_per_min": 8.0
    },
    {
        "name": "High Knees",
        "name_en": "High Knees",
        "category": "cardio",
        "muscle_primary": "Cardiovascular, Flexores da anca",
        "muscle_secondary": "Core, Quadricípites",
        "difficulty": "iniciante",
        "equipment": "Peso corporal",
        "image_url": "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400",
        "video_url": "https://www.youtube.com/watch?v=D0Pw9WGJ0II",
        "instructions": "1. De pé, corre no lugar\n2. Eleva joelhos à altura da anca\n3. Braços em movimento de corrida\n4. Aterra na ponta dos pés\n5. Ritmo rápido",
        "tips": "Foca em trazer joelhos alto, não em velocidade dos pés.",
        "common_mistakes": "Joelhos baixos, inclinar para trás, aterrar nos calcanhares",
        "default_sets": 3,
        "default_reps": "30-45 seg",
        "default_rest_sec": 30,
        "is_compound": 1,
        "calories_per_min": 9.0
    },
    {
        "name": "Box Jumps",
        "name_en": "Box Jumps",
        "category": "cardio",
        "muscle_primary": "Quadricípites, Glúteos",
        "muscle_secondary": "Gémeos, Core",
        "difficulty": "intermedio",
        "equipment": "Box/Plataforma",
        "image_url": "https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=400",
        "video_url": "https://www.youtube.com/watch?v=52r_Ul5k03g",
        "instructions": "1. De pé frente ao box\n2. Baixa ligeiramente as ancas\n3. Salta explosivamente para o box\n4. Aterra suavemente com os pés completos\n5. Fica de pé, desce e repete",
        "tips": "Começa com altura baixa. Aterra suavemente em posição de agachamento.",
        "common_mistakes": "Box muito alto, aterrar na ponta dos pés, não estender no topo",
        "default_sets": 3,
        "default_reps": "8-12",
        "default_rest_sec": 60,
        "is_compound": 1,
        "calories_per_min": 10.0
    },
    
    # ==================== FULL BODY ====================
    {
        "name": "Kettlebell Swing",
        "name_en": "Kettlebell Swing",
        "category": "full_body",
        "muscle_primary": "Glúteos, Isquiotibiais, Core",
        "muscle_secondary": "Ombros, Costas, Antebraços",
        "difficulty": "intermedio",
        "equipment": "Kettlebell",
        "image_url": "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=400",
        "video_url": "https://www.youtube.com/watch?v=YSxHifyI6s8",
        "instructions": "1. Pés mais largos que ombros\n2. Kettlebell entre os pés\n3. Hip hinge para trás, agarra\n4. Swing para trás entre pernas\n5. Impulsiona ancas para frente\n6. KB sobe até altura dos ombros",
        "tips": "É um hip hinge, não um squat. O poder vem das ancas, não dos braços.",
        "common_mistakes": "Usar braços para levantar, agachamento em vez de hinge, arquear costas",
        "default_sets": 3,
        "default_reps": "15-20",
        "default_rest_sec": 60,
        "is_compound": 1,
        "calories_per_min": 12.0
    },
    {
        "name": "Turkish Get-Up",
        "name_en": "Turkish Get-Up",
        "category": "full_body",
        "muscle_primary": "Core, Ombros",
        "muscle_secondary": "Full body estabilização",
        "difficulty": "avancado",
        "equipment": "Kettlebell ou Halter",
        "image_url": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
        "video_url": "https://www.youtube.com/watch?v=0bWRPC6gdPg",
        "instructions": "1. Deitado, KB no braço estendido\n2. Flete joelho do mesmo lado\n3. Rola para cotovelo, depois mão\n4. Levanta anca, passa perna para trás\n5. Fica de pé com KB sempre em cima\n6. Inverte para voltar ao chão",
        "tips": "Exercício complexo. Aprende cada passo. Olhar sempre para o KB.",
        "common_mistakes": "Perder posição do KB, saltar passos, usar peso excessivo",
        "default_sets": 2,
        "default_reps": "3-5 cada lado",
        "default_rest_sec": 90,
        "is_compound": 1,
        "calories_per_min": 8.0
    },
    {
        "name": "Clean and Press",
        "name_en": "Clean and Press",
        "category": "full_body",
        "muscle_primary": "Ombros, Pernas, Core",
        "muscle_secondary": "Trapézio, Tríceps, Costas",
        "difficulty": "avancado",
        "equipment": "Barra ou Halteres",
        "image_url": "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400",
        "video_url": "https://www.youtube.com/watch?v=rlOQysEfmQM",
        "instructions": "1. Barra no chão, pegada à largura dos ombros\n2. Clean: puxa explosivamente às clavículas\n3. 'Catch' em posição de front squat\n4. Press: empurra barra acima da cabeça\n5. Baixa às clavículas, depois ao chão",
        "tips": "Movimento olímpico complexo. Aprende clean e press separadamente primeiro.",
        "common_mistakes": "Técnica pobre no clean, arquear costas no press, peso excessivo",
        "default_sets": 4,
        "default_reps": "5-6",
        "default_rest_sec": 120,
        "is_compound": 1,
        "calories_per_min": 11.0
    },
    {
        "name": "Thruster",
        "name_en": "Thruster",
        "category": "full_body",
        "muscle_primary": "Quadricípites, Ombros",
        "muscle_secondary": "Glúteos, Core, Tríceps",
        "difficulty": "intermedio",
        "equipment": "Barra ou Halteres",
        "image_url": "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400",
        "video_url": "https://www.youtube.com/watch?v=oDdkytliOqE",
        "instructions": "1. Barra/halteres nas clavículas (front rack)\n2. Faz um front squat completo\n3. Explode para cima\n4. Usa momentum para press acima da cabeça\n5. Baixa às clavículas e repete",
        "tips": "Movimento fluido. A subida do squat alimenta o press.",
        "common_mistakes": "Separar squat e press, não usar momentum, cotovelos baixos",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_sec": 90,
        "is_compound": 1,
        "calories_per_min": 13.0
    },
]


def seed_exercises():
    """Popula a base de dados com exercícios."""
    db = SessionLocal()
    try:
        # Verificar se já existem exercícios
        existing = db.query(Exercise).count()
        if existing > 0:
            print(f"⚠️  Base de dados já tem {existing} exercícios. A saltar seed.")
            return
        
        # Inserir exercícios
        for ex_data in EXERCISES:
            exercise = Exercise(**ex_data)
            db.add(exercise)
        
        db.commit()
        print(f"✅ {len(EXERCISES)} exercícios inseridos com sucesso!")
        
        # Mostrar resumo por categoria
        from sqlalchemy import func
        results = db.query(
            Exercise.category,
            func.count(Exercise.id)
        ).group_by(Exercise.category).all()
        
        print("\n📊 Resumo por categoria:")
        for cat, count in results:
            print(f"   • {cat}: {count} exercícios")
            
    except Exception as e:
        db.rollback()
        print(f"❌ Erro ao inserir exercícios: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_exercises()
