"""Reusable pptx building blocks for the LAPHIS deck."""

from .theme import (
    BG_DEEP,
    BG_GRAD_END,
    PANEL,
    PANEL_HI,
    BORDER,
    BORDER_HI,
    TEXT,
    TEXT_DIM,
    TEXT_MUTED,
    ACCENT,
    ACCENT_2,
    ACCENT_SOFT,
    SUCCESS,
    WARN,
    SLIDE_W,
    SLIDE_H,
)
from .fills import gradient_fill, solid, no_line, set_line
from .primitives import (
    bg,
    textbox,
    multi_text,
    panel,
    gradient_panel,
    accent_dot,
    chip,
)
from .slide_chrome import slide_header, footer

__all__ = [
    "BG_DEEP",
    "BG_GRAD_END",
    "PANEL",
    "PANEL_HI",
    "BORDER",
    "BORDER_HI",
    "TEXT",
    "TEXT_DIM",
    "TEXT_MUTED",
    "ACCENT",
    "ACCENT_2",
    "ACCENT_SOFT",
    "SUCCESS",
    "WARN",
    "SLIDE_W",
    "SLIDE_H",
    "gradient_fill",
    "solid",
    "no_line",
    "set_line",
    "bg",
    "textbox",
    "multi_text",
    "panel",
    "gradient_panel",
    "accent_dot",
    "chip",
    "slide_header",
    "footer",
]
